"use strict";
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHTML=(value)=>String(value??"").replace(/[&<>'"]/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[character]));
const labels={E01:"Brief fidelity",E02:"Creative directions",E03:"Design system",E04:"Information design",E05:"References & rights",E06:"Production",E07:"Independent review",E08:"Future memory"};
let snapshot=null;
let selectedElement=null;
let session=null;
let activeView=["create","studio","ops"].includes(new URLSearchParams(location.search).get("view"))?new URLSearchParams(location.search).get("view"):"studio";

async function getJSON(path){const response=await fetch(path),payload=await response.json();if(!response.ok)throw new Error(payload.error||`Error HTTP ${response.status}`);return payload}
function stageNodes(){return snapshot.nodes.filter((node)=>node.node_type==="ENGINE_STAGE").slice(-8)}
function latestRecord(){return snapshot.documents.at(-1)||null}
function latestDocument(){return latestRecord()?.document||null}
function announceHandoff(message){$('#handoff-announcement').textContent=message}
function selectStage(node,button){$$('.stage-list button').forEach((item)=>item.classList.remove('active'));button.classList.add('active');$('#inspector-heading').textContent=labels[node.payload.engine]||node.payload.engine;$('#inspector-content').innerHTML=`<div class="fact-row"><span>Disposición</span><strong>${escapeHTML(node.payload.disposition)}</strong></div><div class="fact-row"><span>Node</span><strong>${escapeHTML(node.node_id)}</strong></div><div class="fact-row"><span>SHA-256</span><strong>${escapeHTML(node.content_hash)}</strong></div><div class="fact-row"><span>Reasons</span><div class="tag-list">${(node.payload.reasons.length?node.payload.reasons:["SIN BLOQUEOS"]).map((reason)=>`<i>${escapeHTML(reason)}</i>`).join('')}</div></div>`}
function selectElement(element){selectedElement=element.element_id;$$('.design-element').forEach((button)=>button.classList.toggle('active',button.dataset.element===selectedElement));$('#inspector-heading').textContent=element.element_id;const facts=[["Tipo",element.element_type],["Claims",element.claim_refs],["Evidencia",element.evidence_refs],["Limitaciones",element.limitation_refs],["Tokens",element.token_refs],["Rights",element.rights_state],["Accesibilidad",element.accessibility_label],["Lineage",element.lineage_refs]];const edit=element.editable?`<form id="edit-form" class="edit-form"><label for="edit-value">Contenido de la nueva versión</label><textarea id="edit-value" required maxlength="4000">${escapeHTML(element.content)}</textarea><button type="submit">Guardar nueva versión</button><p class="edit-help">Crea un hijo, diff e invalidación. No publica ni valida.</p></form>`:'';$('#inspector-content').innerHTML=facts.map(([label,value])=>`<div class="fact-row"><span>${label}</span>${Array.isArray(value)?`<div class="tag-list">${(value.length?value:["NINGUNO"]).map((item)=>`<i>${escapeHTML(item)}</i>`).join('')}</div>`:`<strong>${escapeHTML(value)}</strong>`}</div>`).join('')+edit;$('#edit-form')?.addEventListener('submit',(event)=>saveEdit(event,element))}
async function saveEdit(event,element){event.preventDefault();const form=event.currentTarget,button=$('button',form),status=$('#edit-status'),record=latestRecord(),value=$('#edit-value').value;button.disabled=true;status.className='edit-status';status.textContent='Guardando una nueva versión trazable…';try{const createdAt=new Date().toISOString(),editId=crypto.randomUUID();const response=await fetch('/api/edits',{method:'POST',headers:{'Content-Type':'application/json','X-SICTrA-Edit-Token':session.edit_token},body:JSON.stringify({edit_id:editId,base_version_id:record.version_id,base_content_hash:record.content_hash,element_id:element.element_id,field:'content',value,actor_id:'DESIGN-STUDIO-LOCAL',created_at:createdAt})}),payload=await response.json();if(!response.ok)throw new Error(payload.error||`Error HTTP ${response.status}`);status.innerHTML=`<strong>Nueva versión guardada</strong><div class="diff-summary"><strong>${escapeHTML(payload.diff.domains.join(' + '))}</strong><span>Conserva ${escapeHTML(payload.invalidation.preserved.join(', ')||'ningún motor')} · Reejecuta ${escapeHTML(payload.invalidation.reexecute.join(', '))}</span></div>`;await load(false)}catch(failure){status.className='edit-status error';status.textContent=`No se guardó: ${failure.message}`}finally{button.disabled=false}}
const csv=(value)=>String(value||'').split(',').map((item)=>item.trim()).filter(Boolean);
async function compileCreate(event){event.preventDefault();const form=event.currentTarget,button=$('.compile-button',form),seal=$('#handoff-seal'),data=Object.fromEntries(new FormData(form));button.disabled=true;seal.className='handoff-seal';seal.innerHTML='<span>Handoff Seal</span><strong>Compilando…</strong><p>Verificando evidencia, intención y derechos.</p>';announceHandoff('Compilando handoff.');const payload={create_id:crypto.randomUUID(),object_id:data.object_id,source_identity:data.source_identity,fact_ids:csv(data.fact_ids),evidence_refs:csv(data.evidence_refs),certainty:data.certainty,contradictions:csv(data.contradictions),authority_reference:data.authority_reference,temporal_state:'CURRENT',provenance_refs:csv(data.provenance_refs),audience:data.audience,decision:data.decision,task:data.task,channel:data.channel,success_criterion:data.success_criterion,accessibility_requirements:csv(data.accessibility_requirements),legal_constraints:csv(data.legal_constraints),channel_constraints:csv(data.channel_constraints),references_declared:data.references_declared==='on',brand_manifest_ref:data.brand_manifest_ref||null,reference_rights_manifest_ref:data.reference_rights_manifest_ref||null,uncertainty:csv(data.uncertainty),non_claims:csv(data.non_claims),created_at:new Date().toISOString()};try{const response=await fetch('/api/create',{method:'POST',headers:{'Content-Type':'application/json','X-SICTrA-Edit-Token':session.edit_token},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||`Error HTTP ${response.status}`);if(result.disposition==='CONTINUE'){seal.className='handoff-seal continue';seal.innerHTML=`<span>Handoff Seal · CONTINUE</span><strong>Listo para E01</strong><p>${escapeHTML(result.envelope.fingerprint)}</p>`;announceHandoff('Handoff listo para E01.')}else{seal.className='handoff-seal return';seal.innerHTML=`<span>Handoff Seal · RETURN_UPSTREAM</span><strong>Repara el origen</strong><p>No se creó un sobre utilizable.</p><ul>${result.reasons.map((reason)=>`<li>${escapeHTML(reason)}</li>`).join('')}</ul>`;announceHandoff(`Handoff devuelto al origen. Faltan ${result.reasons.length} datos o validaciones.`)}await load(false)}catch(failure){seal.className='handoff-seal return';seal.innerHTML=`<span>Handoff Seal · ERROR</span><strong>No se compiló</strong><p>${escapeHTML(failure.message)}</p>`;announceHandoff('No se compiló el handoff.')}finally{button.disabled=false}}
function latestExecution(){const resumes=snapshot.nodes.filter((node)=>node.node_type==="ORCHESTRATOR_RESUME");if(resumes.length){const resume=resumes.at(-1),stages=snapshot.nodes.filter((node)=>node.node_type==="ENGINE_STAGE_RESUME"&&node.node_id.startsWith(`${resume.node_id}-`));return{resume,stages}}return{resume:null,stages:stageNodes()}}
function renderOps(){const registry=snapshot.nodes.find((node)=>node.node_type==="ENGINE_REGISTRY"),{resume,stages}=latestExecution(),executed=stages.filter((node)=>(node.payload.execution_state||"EXECUTED")==="EXECUTED").length,reused=stages.filter((node)=>node.payload.execution_state==="REUSED_CHECKPOINT").length;$('#ops-summary').innerHTML=`<article><span>Registry fijado</span><strong>${registry?escapeHTML(registry.content_hash.slice(0,12)):"NO REGISTRADO"}</strong><small>${registry?escapeHTML(registry.payload.state):"RETURN_UPSTREAM"}</small></article><article><span>Trabajo nuevo</span><strong>${executed} / 8</strong><small>Motores ejecutados</small></article><article><span>Estado conservado</span><strong>${reused} / 8</strong><small>Motores rehidratados</small></article><article><span>Autoridad</span><strong>LOCAL</strong><small>NOT_ACCEPTED</small></article>`;$('#execution-tape').innerHTML=stages.map((node)=>{const state=node.payload.execution_state||"EXECUTED",wasReused=state==="REUSED_CHECKPOINT";return`<li class="${wasReused?'reused':'executed'}"><span class="tape-index">${escapeHTML(node.payload.engine)}</span><div><strong>${escapeHTML(labels[node.payload.engine]||node.payload.engine)}</strong><small>${wasReused?'Reutilizado · sin ejecución nueva':'Ejecutado en este recorrido'}</small></div><i>${escapeHTML(node.payload.disposition)}</i></li>`}).join('');const checks=[["Registry",registry?"PINNED_NOT_ACCEPTED":"MISSING"],["Resume",resume?resume.payload.disposition:"RUN INICIAL"],["Publicación",snapshot.authority.publication],["Aceptación",snapshot.authority.acceptance],["Project Graph","READ MODEL"]];$('#integrity-list').innerHTML=checks.map(([label,value])=>`<div class="integrity-row"><span>${escapeHTML(label)}</span><strong>${escapeHTML(value)}</strong></div>`).join('')}
const valueKey=(value)=>JSON.stringify(value??null);
function versionChanges(record){const parent=snapshot.documents.find((item)=>item.version_id===record.parent_version_id);if(!parent)return[];const before=new Map(parent.document.elements.map((item)=>[item.element_id,item])),after=new Map(record.document.elements.map((item)=>[item.element_id,item])),fields={content:'CONTENT',geometry:'GEOMETRY',token_refs:'STYLE',asset_refs:'ASSET',accessibility_label:'ACCESSIBILITY',rights_state:'RIGHTS'},changes=[];for(const id of new Set([...before.keys(),...after.keys()])){const left=before.get(id),right=after.get(id);if(!left||!right){changes.push({element:id,field:'element',domain:'STRUCTURE',before:left?'present':'missing',after:right?'present':'missing'});continue}for(const [field,domain] of Object.entries(fields)){if(valueKey(left[field])!==valueKey(right[field]))changes.push({element:id,field,domain,before:valueKey(left[field]),after:valueKey(right[field])})}}return changes}
function showVersion(record,button){$$('#version-list button').forEach((item)=>item.classList.remove('active'));button.classList.add('active');const changes=versionChanges(record),target=$('#visual-diff');target.innerHTML=changes.length?`<strong>${changes.length} cambio${changes.length===1?'':'s'} desde el padre</strong><p>${escapeHTML(record.parent_version_id)} → ${escapeHTML(record.version_id)}</p>${changes.map((change)=>`<div class="diff-entry"><span>${escapeHTML(change.domain)} · ${escapeHTML(change.element)}</span><strong>${escapeHTML(change.field)}</strong><small>${escapeHTML(change.before)} → ${escapeHTML(change.after)}</small></div>`).join('')}`:`<strong>Versión raíz</strong><p>No existe un padre que comparar. El documento permanece inmutable.</p>`}
function renderHistory(){const records=snapshot.documents;$('#version-list').innerHTML=records.map((record,index)=>`<li><button type="button" data-version="${escapeHTML(record.version_id)}"><strong>${escapeHTML(record.version_id)}</strong><span>${index===0?'Raíz':`${versionChanges(record).length} cambios`} · ${escapeHTML(record.document.state)}</span></button></li>`).join('');$$('[data-version]').forEach((button)=>button.addEventListener('click',()=>showVersion(records.find((record)=>record.version_id===button.dataset.version),button)));const latest=records.at(-1),button=latest&&$(`[data-version="${latest.version_id}"]`);if(latest&&button)showVersion(latest,button);else $('#visual-diff').innerHTML='<strong>Sin versiones</strong><p>El run todavía no produjo un CDD.</p>'}
function setView(view){activeView=view;$$('[data-view]').forEach((button)=>{const active=button.dataset.view===view;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});const studio=view==='studio',ops=view==='ops',create=view==='create';$('#workspace').hidden=!studio;$('#lineage-section').hidden=!studio;$('#history-section').hidden=!studio;$('#ops-view').hidden=!ops;$('#create-view').hidden=!create;const titles={studio:['Design intelligence / Studio','Evidence-first canvas'],ops:['Design intelligence / Ops','Runtime provenance'],create:['Design intelligence / Create','Compile before creation']};$('.command-bar .eyebrow').textContent=titles[view][0];$('.command-bar h1').textContent=titles[view][1]}
function humanStatus(node){if(node.payload.reasons.length)return `${node.payload.reasons.length} límites`;if(node.payload.disposition.includes('READY')||node.payload.disposition.includes('PASS'))return 'Listo · sin promoción';return 'Revisar frontera'}
function render(){const document=latestDocument(),stages=stageNodes();$('#project-badge').textContent=snapshot.project_id;$('#stage-list').innerHTML=stages.map((node)=>`<li><button type="button" data-node="${escapeHTML(node.node_id)}"><span class="stage-code">${escapeHTML(node.payload.engine)}</span><span class="stage-copy"><strong>${escapeHTML(labels[node.payload.engine]||node.payload.engine)}</strong><small>${escapeHTML(humanStatus(node))}</small></span></button></li>`).join('');$$('[data-node]').forEach((button)=>button.addEventListener('click',()=>selectStage(stages.find((node)=>node.node_id===button.dataset.node),button)));if(!document){$('#canvas').innerHTML='<div class="inspector-empty">El run aún no produjo un CDD.</div>';$('#document-state').textContent='Sin documento'}else{const page=document.pages[0];$('#document-state').textContent=document.state;$('#canvas').innerHTML=`<article class="design-page"><header><span>${escapeHTML(document.version_id)}</span><h3>${escapeHTML(page.name)}</h3></header>${document.elements.map((element)=>`<button type="button" class="design-element" data-element="${escapeHTML(element.element_id)}"><strong>${escapeHTML(element.element_type)} · ${escapeHTML(element.element_id)}</strong><span>${escapeHTML(element.content||element.accessibility_label)}</span></button>`).join('')}</article>`;$$('[data-element]').forEach((button)=>button.addEventListener('click',()=>selectElement(document.elements.find((element)=>element.element_id===button.dataset.element)))) }$('#lineage-ribbon').innerHTML=stages.map((node)=>`<li class="${node.payload.disposition.includes('BLOCK')?'blocked':node.payload.reasons.length?'warning':''}"><strong>${escapeHTML(node.payload.engine)}</strong><span>${escapeHTML(labels[node.payload.engine])}</span></li>`).join('');renderOps();renderHistory();setView(activeView);if(document?.elements.length)selectElement(document.elements.find((element)=>element.element_id===selectedElement)||document.elements[0])}
async function load(showLoading=true){const loading=$('#loading'),error=$('#error');loading.hidden=!showLoading;error.hidden=true;try{session||=await getJSON('/api/session');snapshot=await getJSON('/api/project');render();const health=await getJSON('/health');$('#runtime-status').textContent=health.status==='ok'?'Conectado · edición acotada':'Estado desconocido';$('#runtime-dot').classList.toggle('online',health.status==='ok')}catch(failure){error.textContent=`No se pudo abrir la evidencia: ${failure.message}`;error.hidden=false;$('#workspace').hidden=true;$('#lineage-section').hidden=true;$('#history-section').hidden=true;$('#ops-view').hidden=true;$('#create-view').hidden=true}finally{loading.hidden=true}}
document.addEventListener('DOMContentLoaded',()=>{$('#refresh').addEventListener('click',()=>load());$$('[data-view]').forEach((button)=>button.addEventListener('click',()=>setView(button.dataset.view)));$('#create-form').addEventListener('submit',compileCreate);load()});
