"use strict";
const state={catalog:null,scope:"ALL",selected:null};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHTML=(value)=>String(value).replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const stateClass=(value)=>value.toLowerCase();
const metricLabels={coverage_pct:"Cobertura",independent_roots:"Raíces independientes",freshness_pct:"Frescura",uncertainty_reduction_pct:"Reducción de incertidumbre",contradictions_resolved:"Contradicciones resueltas",unresolved_contradictions:"Contradicciones abiertas",elapsed_minutes:"Duración (min)",source_cost_units:"Costo observado"};

async function getJSON(url,options){const response=await fetch(url,options),payload=await response.json();if(!response.ok)throw new Error(payload.error||`Error HTTP ${response.status}`);return payload}
function items(){const all=state.catalog?.investigations||[];return state.scope==="ALL"?all:all.filter((item)=>item.scope.level===state.scope)}
function setView(name){$$('.nav-item').forEach((button)=>{const active=button.dataset.view===name;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});$$('[data-view-panel]').forEach((panel)=>panel.classList.toggle('active',panel.dataset.viewPanel===name));$('#view-name').textContent=$(`.nav-item[data-view="${name}"]`).textContent.trim();window.scrollTo({top:0,behavior:'smooth'})}
function fillSelect(select,values,key,labeler){select.innerHTML=values.map((item)=>`<option value="${escapeHTML(item[key])}">${escapeHTML(labeler(item))}</option>`).join('')}

function renderScopeControls(){const controls=$('#scope-controls');controls.innerHTML=['ALL','GLOBAL','REGIONAL','LOCAL'].map((scope)=>`<button type="button" data-scope="${scope}" aria-pressed="${scope===state.scope}" class="${scope===state.scope?'active':''}">${scope==='ALL'?'Todas':scope}</button>`).join('');$$('[data-scope]',controls).forEach((button)=>button.addEventListener('click',()=>{state.scope=button.dataset.scope;renderOverview()}))}
function renderOverview(){renderScopeControls();const current=items(),sourceCount=current.reduce((sum,item)=>sum+item.evidence_summary.sources,0),roots=current.reduce((sum,item)=>sum+item.evidence_summary.independent_roots,0),contradictions=current.reduce((sum,item)=>sum+item.evidence_summary.contradictions,0);$('#metrics-row').innerHTML=[[current.length,'Investigaciones visibles'],[sourceCount,'Source packets'],[roots,'Raíces independientes'],[contradictions,'Contradicciones explícitas']].map(([value,label])=>`<div class="metric"><strong>${value}</strong><span>${label}</span></div>`).join('');$('#investigation-list').innerHTML=current.length?current.map((item)=>`<article class="investigation-row" role="button" aria-label="Abrir ${escapeHTML(item.title)}" tabindex="0" data-open="${escapeHTML(item.investigation_id)}"><span class="scope-code">${escapeHTML(item.scope.level)}</span><div><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.scope.geography)} · ${item.evidence_summary.independent_roots} raíces independientes</p></div><span class="state-pill ${stateClass(item.status)}">${escapeHTML(item.status)}</span></article>`).join(''):`<div class="pulse-note">No hay investigaciones en esta escala.</div>`;$$('[data-open]').forEach((row)=>{const open=()=>{state.selected=row.dataset.open;$('#investigation-select').value=state.selected;renderDossier();setView('investigations')};row.addEventListener('click',open);row.addEventListener('keydown',(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}})});const total=current.length||1,statuses=[['DELIVERABLE_BOUNDED','Entregable acotado'],['RESEARCH_NEEDED','Investigación requerida'],['DRAFT','Borrador']];$('#epistemic-pulse').innerHTML=statuses.map(([status,label])=>{const count=current.filter((item)=>item.status===status).length,ratio=Math.round((count/total)*100);return `<div class="pulse-meter"><div class="pulse-label"><span>${label}</span><strong>${count}</strong></div><div class="bar" role="img" aria-label="${count} de ${current.length} investigaciones"><i style="width:${ratio}%"></i></div></div>`}).join('')+`<div class="pulse-note">Distribución de estados; no mezcla métricas entre scopes ni produce una predicción.</div>`}

function renderDossier(){const item=state.catalog.investigations.find((entry)=>entry.investigation_id===$('#investigation-select').value)||state.catalog.investigations[0];state.selected=item.investigation_id;$('#investigation-detail').innerHTML=`<article class="dossier"><section class="panel dossier-head"><div><span class="section-kicker">${escapeHTML(item.investigation_id)}</span><h3>${escapeHTML(item.title)}</h3><p class="dossier-question">${escapeHTML(item.question)}</p><div class="evidence-tags"><span class="state-pill ${stateClass(item.status)}">${escapeHTML(item.status)}</span><span>${escapeHTML(item.certainty)} / ${escapeHTML(item.confidence)}</span></div></div><div class="scope-table">${[['Escala',item.scope.level],['Geografía',item.scope.geography],['Industria',item.scope.industry],['Actor',item.scope.actor],['Modalidad',item.scope.mode],['Período',item.scope.period]].map(([label,value])=>`<div><span>${label}</span><strong>${escapeHTML(value)}</strong></div>`).join('')}</div></section><section class="insight-banner"><span>Insight acotado</span><p>${escapeHTML(item.signal)}</p></section><div class="dossier-grid"><section class="panel"><div class="panel-head"><div><span class="section-kicker">Claims</span><h2>${item.claims.length} afirmaciones</h2></div></div><ul class="compact-list">${item.claims.map((claim)=>`<li><strong>${escapeHTML(claim.text)}</strong><span>${escapeHTML(claim.type)} · ${escapeHTML(claim.state)} · ${claim.independent_roots} raíces</span>${claim.contradiction?`<span class="limitation">Contradicción: ${escapeHTML(claim.contradiction)}</span>`:''}</li>`).join('')}</ul></section><section class="panel"><div class="panel-head"><div><span class="section-kicker">Límites</span><h2>No-claims del expediente</h2></div></div><ul class="compact-list">${item.limitations.map((limit)=>`<li><strong>${escapeHTML(limit)}</strong><span>Restricción preservada en el handoff</span></li>`).join('')}</ul></section></div></article>`}

function syncStrategyOptions(){const item=state.catalog.investigations.find((entry)=>entry.investigation_id===$('#strategy-investigation').value);fillSelect($('#strategy-left'),item.strategies,'strategy_id',(strategy)=>strategy.name);fillSelect($('#strategy-right'),item.strategies,'strategy_id',(strategy)=>strategy.name);if(item.strategies.length>1)$('#strategy-right').selectedIndex=1;$('#strategy-result').innerHTML=''}
async function compareStrategies(){const investigation=$('#strategy-investigation').value,left=$('#strategy-left').value,right=$('#strategy-right').value,target=$('#strategy-result');target.innerHTML=`<div class="loading-state"><span></span>Comparando observaciones…</div>`;try{const data=await getJSON(`/api/comparisons/${encodeURIComponent(investigation)}?left=${encodeURIComponent(left)}&right=${encodeURIComponent(right)}`),result=data.comparison,title=result.verdict==='PREFER_LEFT'?data.left.name:result.verdict==='PREFER_RIGHT'?data.right.name:result.verdict==='INCOMPARABLE'?'Ventajas cruzadas':'No comparable todavía';target.innerHTML=`<div class="comparison"><section class="panel verdict"><div class="verdict-code">${escapeHTML(result.verdict)}</div><div><h3>${escapeHTML(title)}</h3><p>${escapeHTML(result.reason)} Método: ${escapeHTML(result.method)}.</p></div></section><table class="metric-table"><thead><tr><th>Métrica / dirección</th><th>${escapeHTML(data.left.name)}</th><th>${escapeHTML(data.right.name)}</th><th>Ventaja</th></tr></thead><tbody>${result.metric_observations.map((metric)=>`<tr><td>${escapeHTML(metricLabels[metric.metric])}<br><small>${escapeHTML(metric.direction)}</small></td><td class="${metric.advantage===data.left.strategy_id?'advantage':''}">${metric.left}</td><td class="${metric.advantage===data.right.strategy_id?'advantage':''}">${metric.right}</td><td>${escapeHTML(metric.advantage)}</td></tr>`).join('')}</tbody></table></div>`}catch(error){target.innerHTML=`<div class="error-state">${escapeHTML(error.message)}</div>`}}

function renderEvidence(){const item=state.catalog.investigations.find((entry)=>entry.investigation_id===$('#evidence-select').value),sourceTags=item.sources.map((source)=>`<span>${escapeHTML(source.source_id)} · ${escapeHTML(source.root)}</span>`).join(''),claimTags=item.claims.map((claim)=>`<span>${escapeHTML(claim.claim_id)} · ${escapeHTML(claim.state)}</span>`).join(''),contradictions=item.claims.filter((claim)=>claim.contradiction);$('#evidence-spine').innerHTML=`<div class="spine"><article class="spine-node"><span class="section-kicker">E01 · Pregunta</span><h3>${escapeHTML(item.question)}</h3><p>${escapeHTML(item.scope.scope_key)}</p></article><article class="spine-node"><span class="section-kicker">E02 · Fuentes</span><h3>${item.sources.length} packets / ${item.evidence_summary.independent_roots} raíces</h3><p>Las copias correlacionadas no aumentan corroboración.</p><div class="evidence-tags">${sourceTags}</div></article><article class="spine-node"><span class="section-kicker">E04 · Claims</span><h3>${item.claims.length} claims tipados</h3><p>Fact, interpretación, hipótesis y forecast permanecen separados.</p><div class="evidence-tags">${claimTags}</div></article><article class="spine-node ${contradictions.length?'warning':''}"><span class="section-kicker">E05 · Red team</span><h3>${contradictions.length} contradicciones explícitas</h3><p>${contradictions.length?escapeHTML(contradictions.map((claim)=>claim.contradiction).join(' · ')):'No se registraron contradicciones en este fixture.'}</p></article><article class="spine-node"><span class="section-kicker">E08 · Disposición</span><h3>${escapeHTML(item.status)}</h3><p>${escapeHTML(item.signal)}</p></article></div>`}
function renderWatchlists(){const horizons=['7D','30D','90D'];$('#watchlist-grid').innerHTML=horizons.map((horizon)=>`<section class="panel watch-column"><h3>${horizon.replace('D',' días')}</h3>${state.catalog.investigations.map((item)=>{const watch=item.watchlist.find((entry)=>entry.horizon===horizon);return `<article class="watch-item"><strong>${escapeHTML(watch.observable)}</strong><span>${escapeHTML(item.scope.level)} · Trigger: ${escapeHTML(watch.trigger)}</span></article>`}).join('')}</section>`).join('')}

async function runScenario(button){const buttons=$$('[data-scenario]');buttons.forEach((item)=>item.disabled=true);try{const data=await getJSON(`/api/scenarios/${button.dataset.scenario}`,{method:'POST'}),kind=data.summary.status==='COMMITTED'?'good':data.summary.status==='BLOCKED_CORRECTLY'?'blocked':'unexpected';$('#validation-result').className=`panel validation-result ${kind}`;$('#validation-result').innerHTML=`<span class="section-kicker">${escapeHTML(data.summary.status)}</span><h3>${escapeHTML(data.summary.title)}</h3><p>${escapeHTML(data.summary.message)}</p><details><summary>Ver evidencia técnica</summary><pre class="technical">${escapeHTML(JSON.stringify(data.report,null,2))}</pre></details>`}catch(error){$('#validation-result').className='panel validation-result unexpected';$('#validation-result').innerHTML=`<span class="section-kicker">ERROR</span><h3>No se completó la prueba</h3><p>${escapeHTML(error.message)}</p>`}finally{buttons.forEach((item)=>item.disabled=false)}}
function bind(){$$('.nav-item').forEach((button)=>button.addEventListener('click',()=>setView(button.dataset.view)));$$('[data-jump]').forEach((button)=>button.addEventListener('click',()=>setView(button.dataset.jump)));$('#investigation-select').addEventListener('change',renderDossier);$('#strategy-investigation').addEventListener('change',syncStrategyOptions);$('#compare').addEventListener('click',compareStrategies);$('#evidence-select').addEventListener('change',renderEvidence);$$('[data-scenario]').forEach((button)=>button.addEventListener('click',()=>runScenario(button)));$('#refresh').addEventListener('click',loadWorkspace)}
async function loadWorkspace(){$('#loading').hidden=false;$('#error').hidden=true;try{state.catalog=await getJSON('/api/workspace');state.selected||=state.catalog.investigations[0]?.investigation_id;fillSelect($('#investigation-select'),state.catalog.investigations,'investigation_id',(item)=>`${item.scope.level} · ${item.title}`);$('#investigation-select').value=state.selected;fillSelect($('#strategy-investigation'),state.catalog.investigations,'investigation_id',(item)=>`${item.scope.level} · ${item.title}`);fillSelect($('#evidence-select'),state.catalog.investigations,'investigation_id',(item)=>`${item.scope.level} · ${item.title}`);renderOverview();renderDossier();syncStrategyOptions();renderEvidence();renderWatchlists();const health=await getJSON('/health');$('#runtime-status').textContent=health.status==='ok'?'Conectado · fixture':'Estado desconocido';$('.local-dot').classList.toggle('online',health.status==='ok')}catch(error){$('#error').textContent=`No se pudo cargar el workspace: ${error.message}`;$('#error').hidden=false}finally{$('#loading').hidden=true}}
document.addEventListener('DOMContentLoaded',()=>{bind();loadWorkspace()});
